### ISSUE TITLE
QueryType нарушает постановку и видимо в этом корень непонимания

### ISSUE THREAD

**Issue by comdiv** [iskkonekb/kuvera#11]
https://github.com/iskkonekb/kuvera/blob/9f30c1354cb10ee676d7daf1aae0a009c4a08f6f/iskkonekb.kuvera.model/Query.cs#L15

Query по идее значения возвращает, а не наборы, а тут наборы

А тут QueryType Select, хотя в #6 красной нитью проходит не Select, а Primary.
Получается неправильно воспринято слово Primary - Primary это первичное хранимое значение, это даже не обязательно что-то из базы, просто что-то что уже никуда не раскладывается, дословно "первичное". 

Видимо отсюда и растут ноги для #10

**Comment by Brahmi108** [comment]
corrected
