### ISSUE TITLE
Надо провести общий рефакторинг Query

### ISSUE THREAD

**Issue by comdiv** [iskkonekb/kuvera#12]
https://github.com/iskkonekb/kuvera/blob/9f30c1354cb10ee676d7daf1aae0a009c4a08f6f/iskkonekb.kuvera.model/Query.cs#L30

Неудачные имена, прошу переименовать и в целом провести рефакторинг класса

1. Не надо испьзовать публичные поля, никогда, только свойства - даже если это простое значение, то значит `public int X {get;set;}`, но не просто `public int X` - иначе это делать себе самому пакость - поля нельзя вынести в интерфейс, свойства можно. Поля это всегда просто значения, свойства позволяют реализовывать логики отложенной инициализации и валидации например, поля нельзя перекрыть в дочернем классе, свойства можно, поля нельзя сделать полноценно ридонли или врайтонли - свойства можно
2. Переименовать
`where` - плохо, во первых пересекается с системным словом, во-вторых  не совсем соответствует назначению и читается плохо `List<Condition> where` ну раз список условий, то и называть налдо "условия", то есть Conditions
`subQ` - ну как бы делать всякие сокращенные имена - это себе же жизнь потом портить, надо полными словами все именовать полноценными, в данном случае подойдет `Children` как в #6 или может более корректно `SubQueries`  чтобы не путалось с отношением с Parent, но не `subQ`
В C# есть соглашения о правильном именовании, публичные члены класса должны быть PascalCase, а не camelCase (как например в Java принято), то есть без особой нужды не надо использовать имен на маленькие буквы

3. Связано со свойствами 
Вот так как сейчас:
```
 public List<Query> subQ;
public Query(){
     subQ = new List<Query>();  
}
```
это плохо - и по причине свойств и по причине лишних строк, только так нормально читается и функционально соответствует:
```
public List<Query> SubQueries {get; private set;} = new List<Query>();
```
Все - это свойство, только на чтение, устанавливается при создании объекта, явно прописывать в конструкторе не надо

**Comment by Brahmi108** [comment]
ok. Сделал
