### ISSUE TITLE
Надо подчистить интерфейс IEngine - в нем остались всякие SaldoOut

### ISSUE THREAD

**Issue by comdiv** [iskkonekb/kuvera#7]
https://github.com/iskkonekb/kuvera/blob/9f30c1354cb10ee676d7daf1aae0a009c4a08f6f/iskkonekb.kuvera.engine/IEngine.cs#L31

в соответствии же с задачей #6 - должно было только Sum и Select остаться

**Comment by comdiv** [comment]
Это был первый пункт рефакторинга, почему-то не выполнен:

> Что должно быть (на крупном плане)

> Engine - по своей роли это пользовательский фасад для обработки зпросов к модели, 
> соответственно должен строиться как строятся подобные вещи в базах данных
> у Engine должен быть только один метод (реально единственный публичный метод)
> public decimal Sum( Query query )

**Comment by Brahmi108** [comment]
done
