### ISSUE TITLE
Разнести классы в файле Query.cs на отдельные файлы

### ISSUE THREAD

**Issue by comdiv** [iskkonekb/kuvera#9]
https://github.com/iskkonekb/kuvera/blob/9f30c1354cb10ee676d7daf1aae0a009c4a08f6f/iskkonekb.kuvera.model/Query.cs#L1

**Comment by Brahmi108** [comment]
Фагим, здесь один класс. Если речь про структуру и enum то я отел бы их иметь рядом для удобства работы с ними. Поясните, пожалуйста, зачем это делать и какие преимущества мы получим?

**Comment by Brahmi108** [comment]
done
